### ISSUE TITLE
Exceptions in loading assemblies to ConfigureApplicationParts

### ISSUE THREAD

**Issue by oleksandrmelnychenko** [OrleansContrib/Orleankka#147] opened 2018-10-23 18:49 UTC

**Comment by yevhen** [comment] 2018-10-24 07:08
?

**Comment by oleksandrmelnychenko** [comment] 2018-11-01 16:59
[ConsoleApp3.zip](https://github.com/OrleansContrib/Orleankka/files/2539343/ConsoleApp3.zip)

**Comment by oleksandrmelnychenko** [comment] 2018-11-01 17:00
Please help, it's default implementation, can you tell me, what I'm doing wrong?
![image](https://user-images.githubusercontent.com/7407215/47866773-60352380-de08-11e8-8a8e-6b9a75c5f443.png)

**Comment by aprooks** [comment] 2018-11-01 18:36
Hi, you should register new assembly like this:

```
    sb.ConfigureApplicationParts(fun x ->
           x.AddFromAppDomain().WithCodeGeneration()|> ignore
           x.AddApplicationPart(typeof<GreeterMessage>.Assembly).WithCodeGeneration() |> ignore
           ) |> ignore
```

**Comment by oleksandrmelnychenko** [comment] 2018-11-01 19:03
I have tried to do many variations, but always catch exceptions.
![image](https://user-images.githubusercontent.com/7407215/47873310-8c0cd500-de19-11e8-98b7-506c5b507de1.png)

**Comment by oleksandrmelnychenko** [comment] 2018-11-01 19:28
Thanks, hope it will be resolved. I want to setup it in a big project, akka.net will wait.

**Comment by aprooks** [comment] 2018-11-01 19:29
OK there were 2 issues. 

First, add a reference to Orleans specific object like here: https://github.com/aprooks/orleankka-fsharp-intro/blob/master/FByke.Contracts/Library.fs#L23-L29 (can be a separate file as well)

second, remove application part of host, since you don't have any grain classes there. Like this:

```
    cb.ConfigureApplicationParts(fun x ->
            x.AddApplicationPart(typeof<GreeterMessage>.Assembly).WithCodeGeneration() |> ignore )  |> ignore
```

the second issue seems to be a bug. I will test again and file a proper report if it is confirmed

**Comment by oleksandrmelnychenko** [comment] 2018-11-02 07:17
Have added, that "type". It's ok with it. Thanks for the quick response !!!

**Comment by aprooks** [comment] 2018-11-02 09:58
No problem. Feel free to join gitter channel https://gitter.im/OrleansContrib/Orleankka for quick questions. 

I'll close this issue and create followups

**Closed by aprooks** 2018-11-02 09:58 UTC
